[pytest]
addopts = --reportportal --headed
markers =
    e2e: End-to-end tests
    order: Test execution order
python_files = test_*.py

# ReportPortal Settings
rp_endpoint = http://localhost:8080
rp_api_key = my_p0DSm5IVS6aUgFqSp1HQGGGkL3gHJHVCkBQCeCOntm2Di5O955cdDFvUNRlkPSVS
rp_project = superadmin_personal
rp_launch = eBay_E2E_Tests
rp_verify_ssl = False
rp_log_level = INFO

# CLI Logging
log_cli = true
log_cli_level = INFO
log_format = %(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)
log_date_format = %Y-%m-%d %H:%M:%S