[pytest]
addopts = --reportportal --headed
markers =
    e2e: End-to-end tests
    order: Test execution order
python_files = test_*.py

# Основные настройки
rp_endpoint = http://localhost:8080
rp_api_key = my_p0DSm5IVS6aUgFqSp1HQGGGkL3gHJHVCkBQCeCOntm2Di5O955cdDFvUNRlkPSVS
rp_project = superadmin_personal
rp_launch = eBay_E2E_Tests
rp_verify_ssl = False
log_cli = true
log_cli_level = INFO